### DISCUSSION TITLE
NSS softokn doesn't list the deeper URIs with the PKCS#11 provider

### DISCUSSION THREAD

**Discussion by Hussain1811** [openssl-projects/pkcs11-provider#400] [Q&A]
i pointed `pkcs11-module-path` to `libsoftokn3.so` (built via https://github.com/nss-dev/nss) and ended up in below error:

```
/opt/openssl/bin/openssl pkey -in "pkcs11:type=public" -pubin -pubout -out testkey.pub -provider pkcs11
Could not find private key of Public Key from pkcs11:type=public
```

Also, the storeutl command doesn't list anything:
```
/opt/openssl/bin/openssl storeutl "pkcs11:type=public"
Total found: 0
```
```
/opt/openssl/bin/openssl storeutl -r "pkcs11:type=public"
Total found: 0
```
My `openssl.cnf` looks like below:
```
[openssl_init]
providers = provider_sect

# List of providers to load
[provider_sect]
default = default_sect
oqsprovider = oqsprovider_sect
pkcs11 = pkcs11_sect

[default_sect]
activate = 1

[oqsprovider_sect]
activate = 1

[pkcs11_sect]
module = /mnt/c/Users/SadiqHussainM/pkcs11-provider/builddir/src/pkcs11.so
pkcs11-module-path = /mnt/c/Users/SadiqHussainM/nss_stuff/dist/Debug/lib/libsoftokn3.so
activate = 1
```
The PKCS#11 provider is listed too:
```
/opt/openssl/bin/openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.3.0
    status: active
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.6.1-dev
    status: active
  pkcs11
    name: PKCS#11 Provider
    version: 3.3.0
    status: active
```

Could anyone please guide how i can proceed further in order to play around with PKCS#11 with openssl? (listing slots, tokens, generating keys, doing crypto operations etc)
